apiVersion: batch/v1
kind: Job
metadata:
    name: pn-gen
spec:
    template:
        spec:
            containers:
            - name: pn-generator
              image: maho/pn-generator:0.1
              env:
              - name: A_START_NUM
                value: "2"
              - name: A_SIZE_NUM
                value: "10**5"
            restartPolocy: Never
        backoffLimit:4

